version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/site
    ports:
      - 8000:8000
    env_file:
      - ./local.env
  redis:
    image: redis
