version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/site
    ports:
      - 6543:6543
    env_file:
      - ./local.env
